@startuml
'https://plantuml.com/class-diagram

class source.AppInfo {
    {static} +get_name() -> str
    {static} +get_version() -> str
    {static} +get_text_logo() -> str
}

class source.output.Logger {
    -__log_level: LogLevel
    +print_log_message(log_level: LogLevel, message: str)
}

enum source.model.LogLevel {
    ERROR
    DEBUG
    INFO
}

source.model.LogLevel -- source.output.Logger : < owns

class source.model.DriverInfo {
    -__driver_path: str
    -__driver_type: str
    +get_driver_path() -> str
    +get_driver_type() -> str
}

class source.model.ReservationStep1Info {
    -__start_month_tag: str
    -__start_month: str
    -__start_year: str
    -__end_month_tag: str
    -__end_month: str
    -__end_year: str
    -__room_choices: str
    +get_start_month_tag() -> str
    +get_start_month() -> str
    +get_start_year() -> str
    +get_end_month_tag() -> str
    +get_end_month() -> str
    +get_end_year() -> str
    +get_room_choices() -> list
}


class source.model.ConfigurationInfo {
    -__log_level: LogLevel
    -__dry_run: str
    -__driver_type: str
    -__driver_path: str
    -__driver_info: DriverInfo
    -__hon_home_url: str
    -__start_month_tag: str
    -__start_month: str
    -__start_year: str
    -__end_month_tag: str
    -__end_month: str
    -__end_year: str
    -__room_choices: str
    -__reservation_step1_info: ReservationStep1Info

    +get_log_level() -> LogLevel
    +set_log_level(log_level: LogLevel)
    +get_dry_run() -> str
    +set_dry_run(dry_run: str)
    +get_driver_path() -> str
    +set_driver_path(driver_path: str)
    +get_driver_type() -> str
    +set_driver_type(driver_type: str)
    +get_driver_info() -> DriverInfo
    +set_driver_info(driver_info: DriverInfo)
    +get_hon_home_url() -> str
    +set_hon_home_url(hon_home_url: str)
    +get_start_month_tag() -> str
    +set_start_month_tag(start_month_tag: str)
    +get_start_month() -> str
    +set_start_month(start_month: str)
    +get_start_year() -> str
    +set_start_year(start_year: str)
    +get_end_month_tag() -> str
    +set_end_month_tag(end_month_tag: str)
    +get_end_month() -> str
    +set_end_month(end_month: str)
    +get_end_year() -> str
    +set_end_year(end_year: str)
    +get_room_choices() -> str
    +set_room_choices(room_choices: str)
    +get_reservation_step1_info() -> ReservationStep1Info
    +set_reservation_step1_info(reservation_step1_info: ReservationStep1Info)
}

source.model.DriverInfo -- source.model.ConfigurationInfo : < owns
source.model.ReservationStep1Info -- source.model.ConfigurationInfo : < owns

class source.model.Configuration {
    -__configuration_info: ConfigurationInfo
    +get_configuration_info(): ConfigurationInfo
    -__validate(configuration_info: ConfigurationInfo)
    -__init_log_level(log_level: LogLevel)
    -__init_dry_run(dry_run: str)
    -__init_driver_info(configuration_info: ConfigurationInfo)
    -__init_hon_home_url(hon_home_url: str)
    -__init_reservation_step1_info(configuration_info: ConfigurationInfo)
    -__validate_month_tag(month_tag: str, period: str)
    -__validate_month_year(param: str, period: str, validator)
    -__validate_room_choices(room_choices: str)
    {static} -__month_validator(month: str) -> bool
    {static} -__year_validator(year: str) -> bool
    {static} -__room_choice_validator(room_choices: list) -> bool
    {static} -__csv_to_list(csv_param: str) -> list
}

source.model.ConfigurationInfo -- source.model.Configuration : < owns

class source.utils.FileUtils {
    {static} +exists(absolute_file_path: str) -> bool
    {static} +is_dir(absolute_dir_path: str) -> bool
}

class source.validator.ParameterValidator {
    -__argv: list
    +is_valid() -> bool
    +is_help_call() -> bool
    +is_version_call() -> bool
    +is_normal_run_call() -> bool
    +is_dry_run_call() -> bool
    +get_argv() -> list
    -__has_two_arguments() -> bool
    -__parameter_file_exists() -> bool
}

class source.validator.UrlValidator {
    -__url: str
    +is_valid() -> bool
    -__is_valid_url() -> bool
}

class source.infrastructure.RequirementsReader {
    -__file_path: str
    +get_file_path() -> str
    +get_version_of(module_name: str) -> str
    -__prepare_requirements_dict()
}

class source.factory.DriverFactory {
    {static} +get_instance(driver_info: DriverInfo) -> webdriver
}

class source.factory.ConfigurationFactory {
    {static} +build(path_to_yml_file: str)
    {static} -__is_valid_yml_file(path_to_yml_file: str)) -> bool
    {static} -__open_yml_file(path_to_yml_file: str)
    {static} -__build_configuration_from_yml_file(yaml_content: dict) -> Configuration
    {static} -__get_log_level(yaml_content: dict) -> LogLevel
    {static} -__get_log_level_value(log_level_string: str) -> LogLevel
    {static} -__get_dry_run(yaml_content: dict) -> str
    {static} -__get_driver_path(yaml_content: dict) -> str
    {static} -__get_driver_type(yaml_content: dict) -> str
    {static} -__get_hon_home_url(yaml_content: dict) -> str
    {static} -__get_step1_start_month_tag(yaml_content: dict) -> str
    {static} -__get_step1_start_month(yaml_content: dict) -> str
    {static} -__get_step1_start_year(yaml_content: dict) -> str
    {static} -__get_step1_end_month_tag(yaml_content: dict) -> str
    {static} -__get_step1_end_month(yaml_content: dict) -> str
    {static} -__get_step1_end_year(yaml_content: dict) -> str
    {static} -__get_step1_room_choices(yaml_content: dict) -> str
    {static} -__get_key_missing_error_message(exc: KeyError) -> str
}

abstract class source.pages.Page {
    {abstract} +get_url() -> str
    {abstract} +at() -> bool
}

class source.pages.house_of_nations.HomePage implements source.pages.Page {
    -__configuration: Configuration
    -__driver: webdriver
    -__page_title: str
    -__xpath_nav_menu: str
    -__xpath_english_sub_menu: str
    +get_url() -> str
    +at() -> bool
    +get_language_menu() -> webelement
    +get_english_sub_menu() -> webelement
    +get_xpath_english_sub_menu() -> str
    -__set_attributes()
    -__get_nav_menu() -> webelement
}

class source.pages.house_of_nations.EnglishPage implements source.pages.Page {
    -__driver: webdriver
    -__page_url: str
    -__page_title: str
    -__xpath_reservation_button: str
    +get_url() -> str
    +at() -> bool
    +get_reservation_button() -> webelement
    +get_xpath_reservation_button() -> str
    -__set_attributes()
}

class source.pages.house_of_nations.ReservationPage1 implements source.pages.Page {
    -__configuration: Configuration
    -__driver: webdriver
    -__xpath_step_1_div: str
    -__xpath_next_button: str
    -__xpath_start_month_tag: str
    -__id_start_month: str
    -__name_start_year: str
    -__xpath_end_month_tag: str
    -__xpath_end_month: str
    -__xpath_end_year: str
    -__page_title: str
    -__xpath_room_choice_typ0: str
    -__xpath_room_choice_typ1: str
    -__xpath_room_choice_typ2: str
    -__xpath_room_choice_typ3: str
    -__xpath_room_choice_typ4: str
    +get_url() -> str
    +at() -> bool
    +get_next_button() -> webelement
    +get_xpath_next_button() -> str
    +fill_start_month_tag()
    +fill_start_month()
    +fill_start_year()
    +fill_end_month_tag()
    +fill_end_month()
    +fill_end_year()
    +fill_room_choices()
    -__set_attributes()
    -__get_step_1_div() -> webelement
    -__get_start_month_tag_select_element() -> webelement
    -__get_start_month_select_element() -> webelement
    -__get_start_year_select_element() -> webelement
    -__get_end_month_tag_select_element() -> webelement
    -__get_end_month_select_element() -> webelement
    -__get_end_year_select_element() -> webelement
    -__get_room_choice_typ0_checkbox() -> webelement
    -__get_room_choice_typ1_checkbox() -> webelement
    -__get_room_choice_typ2_checkbox() -> webelement
    -__get_room_choice_typ3_checkbox() -> webelement
    -__get_room_choice_typ4_checkbox() -> webelement
    {static} -__find_element(by: str)
}

class source.executor.ApplicationSubmitter {
    -__yaml_file_path: str
    -__configuration: Configuration
    -__logger: Logger
    -__driver: webdriver
    +initialize()
    +set_dry_run_parameter_configuration()
    +go_to_home_page()
    +move_to_english_page_from_home()
    +move_to_reservation_step1_from_english()
    +fill_step1_information_and_move_to_step_2()
    +shutdown()
    +get_logger() -> Logger
    +dry_run_enabled() -> bool
    -__quit_driver()
}

source.output.Logger -- source.executor.ApplicationSubmitter : < owns
source.model.Configuration -- source.executor.ApplicationSubmitter : < owns

class source.executor.AppExecutor {
    -__parameter_validator: ParameterValidator
    -__logger: Logger
    +run()
    -__run_dry()
    -__run_normal()
    -__create_application()
    -__run()
    -__display_begin_message()
    -__handle_pre_steps()
    -__handle_post_steps()
    -__display_help()
    -__get_help_message() -> str
    -__get_artwork() -> str
}

source.validator.ParameterValidator -- source.executor.AppExecutor : < owns

@enduml